subject = ["C", "C++", "Python", "JS", "PHP", "HTML", "MongoDB"]

print(subject[2:])
print(subject[-1])
print("Python" in subject)
print(subject + ["Express"])
print(len(subject))
subject.append("Node")
print(subject)
subject.insert(2,"React")
print(subject)
subject.remove("JS")
print(subject)
subject.sort()
print(subject)
subject.reverse()
print(subject)
subject.pop(1)
print(subject)
subject2 = subject.copy()
print(subject2)
position = subject2.index("C++")
print(position)